spring:
  datasource:
    url: jdbc:mysql://192.168.145.128:3306/rentcloud_customer?createDatabaseIfNotExist=true
    #username: root
    #password: root
    username: admin
    password: admin
    tomcat:
      validation-query: SELECT 1
    dbcp2:
      test-while-idle: true
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    lease:
      duration: 5
    service-url:
      defaultZone: http://172.17.0.4:8762/eureka
  instance:
    instanceId: ${spring.application.name}:${random.int}
    hostname: localhost
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1        
